// ── Уровень 25 ──────────────────────────────────────────────────
LEVELS.push({
  cols: 8, rows: 9,
  time: 320,
  walls: [
    { color: 'cyan', dir: 'top', col: 0, cells: 3 },
    { color: 'purple', dir: 'top', col: 3, cells: 2 },
    { color: 'yellow', dir: 'top', col: 5, cells: 3 },
    { color: 'green', dir: 'left', row: 0, cells: 3 },
    { color: 'red', dir: 'left', row: 3, cells: 3 },
    { color: 'blue', dir: 'left', row: 6, cells: 3 },
    { color: 'purple', dir: 'right', row: 0, cells: 2 },
    { color: 'cyan', dir: 'right', row: 2, cells: 3 },
    { color: 'orange', dir: 'right', row: 5, cells: 2 },
    { color: 'yellow', dir: 'bottom', col: 0, cells: 2 },
    { color: 'green', dir: 'bottom', col: 2, cells: 3 },
    { color: 'red', dir: 'bottom', col: 5, cells: 3 },
  ],
  blocks: [
    { shape: '1x1', col: 3, row: 3 },
    { shape: '1x1', col: 4, row: 3 },
    { shape: '1x1', col: 3, row: 4 },
    { shape: '1x1', col: 4, row: 4 },
    { shape: '1x1', col: 3, row: 5 },
    { shape: '1x1', col: 4, row: 5 },
  ],
  figures: [
    { shape: 'mini_J', color: '#c84bdf', col: 0, row: 0 },
    { shape: 'Z', color: '#ff9800', col: 2, row: 0, outlineColor: '#29b6f6' },
    { shape: '1x2', color: '#29b6f6', col: 7, row: 2 },
    { shape: 'T', color: '#f44336', col: 0, row: 2 },
    { shape: 'L', color: '#29b6f6', col: 0, row: 4, outlineColor: '#c84bdf' },
    { shape: 'mini_L', color: '#ff9800', col: 6, row: 4 },
    { shape: '2x2', color: '#4caf50', col: 1, row: 4, outlineColor: '#f44336' },
    { shape: 'S', color: '#ffc107', col: 4, row: 6 },
    { shape: 'mini_J', color: '#1976d2', col: 6, row: 7 },
    { shape: '1x1', color: '#f44336', col: 3, row: 8 },
    { shape: '1x1', color: '#c84bdf', col: 5, row: 3 },
    { shape: 'J', color: '#f44336', col: 5, row: 0, axis: 'y' },
    { shape: '1x3', color: '#29b6f6', col: 2, row: 6, axis: 'y' },
    { shape: '2x1', color: '#29b6f6', col: 0, row: 8, outlineColor: '#ffc107', axis: 'y' },
  ],
});