// ── Уровень 32 ──────────────────────────────────────────────────
LEVELS.push({
  cols: 10, rows: 11,
  time: 192,
  walls: [
    { color: 'yellow', dir: 'top', col: 0, cells: 2 },
    { color: 'purple', dir: 'top', col: 2, cells: 3 },
    { color: 'cyan', dir: 'top', col: 5, cells: 3 },
    { color: 'red', dir: 'top', col: 8, cells: 2 },
    { color: 'green', dir: 'left', row: 0, cells: 3 },
    { color: 'orange', dir: 'left', row: 3, cells: 3 },
    { color: 'blue', dir: 'left', row: 6, cells: 3 },
    { color: 'purple', dir: 'left', row: 9, cells: 2 },
    { color: 'cyan', dir: 'right', row: 0, cells: 3 },
    { color: 'yellow', dir: 'right', row: 3, cells: 3 },
    { color: 'orange', dir: 'bottom', col: 0, cells: 3 },
    { color: 'blue', dir: 'bottom', col: 3, cells: 2 },
    { color: 'purple', dir: 'bottom', col: 5, cells: 3 },
    { color: 'yellow', dir: 'bottom', col: 8, cells: 2 },
    { color: 'green', dir: 'right', row: 8, cells: 3 },
  ],
  blocks: [
    { shape: '1x1', col: 4, row: 4 },
    { shape: '1x1', col: 5, row: 4 },
    { shape: '1x1', col: 4, row: 5 },
    { shape: '1x1', col: 5, row: 5 },
    { shape: '1x1', col: 4, row: 6 },
    { shape: '1x1', col: 5, row: 6 },
  ],
  figures: [
    { shape: 'L', color: '#ffc107', col: 0, row: 0, outlineColor: '#29b6f6' },
    { shape: 'J', color: '#c84bdf', col: 2, row: 0 },
    { shape: '2x1', color: '#29b6f6', col: 5, row: 0, axis: 'x' },
    { shape: 'T', color: '#1976d2', col: 0, row: 3, outlineColor: '#ffc107' },
    { shape: 'Z', color: '#ff9800', col: 5, row: 2 },
    { shape: '2x2', color: '#29b6f6', col: 7, row: 4, outlineColor: '#4caf50' },
    { shape: 'S', color: '#4caf50', col: 0, row: 7 },
    { shape: 'mini_J', color: '#c84bdf', col: 3, row: 8 },
    { shape: '1x2', color: '#ffc107', col: 8, row: 8 },
    { shape: '1x1', color: '#1976d2', col: 1, row: 10 },
    { shape: '1x1', color: '#ff9800', col: 6, row: 10 },
    { shape: '2x1', color: '#c84bdf', col: 5, row: 9, outlineColor: '#4caf50', axis: 'x' },
    { shape: '1x3', color: '#29b6f6', col: 9, row: 2, outlineColor: '#4caf50', axis: 'y' },
    { shape: 'mini_L', color: '#f44336', col: 8, row: 0, outlineColor: '#ffc107', axis: 'y' },
  ],
});