// ── Уровень 16 ──────────────────────────────────────────────────
LEVELS.push({
  cols: 7, rows: 7,
  time: 170,
  walls: [
    { color: 'green', dir: 'top', col: 0, cells: 3 },
    { color: 'orange', dir: 'top', col: 3, cells: 2 },
    { color: 'green', dir: 'top', col: 5, cells: 2 },
    { color: 'yellow', dir: 'right', row: 0, cells: 1 },
    { color: 'red', dir: 'right', row: 1, cells: 2 },
    { color: 'purple', dir: 'right', row: 3, cells: 1 },
    { color: 'purple', dir: 'bottom', col: 0, cells: 1 },
    { color: 'cyan', dir: 'bottom', col: 1, cells: 3 },
    { color: 'red', dir: 'bottom', col: 4, cells: 2 },
    { color: 'purple', dir: 'bottom', col: 6, cells: 1 },
    { color: 'orange', dir: 'left', row: 5, cells: 2 },
    { color: 'blue', dir: 'left', row: 0, cells: 3 },
    { color: 'red', dir: 'left', row: 3, cells: 2 },
    { color: 'green', dir: 'right', row: 4, cells: 3 },
  ],
  figures: [
    { shape: '1x2', color: '#1e88e5', col: 5, row: 0 },
    { shape: '1x1', color: '#1e88e5', col: 6, row: 0 },
    { shape: 'mini_J', color: '#f44336', col: 5, row: 2 },
    { shape: '1x1', color: '#ffc107', col: 3, row: 3 },
    { shape: '2x1', color: '#1e88e5', col: 5, row: 4 },
    { shape: '1x2', color: '#29b6f6', col: 3, row: 1 },
    { shape: 'mini_L', color: '#ff9800', col: 0, row: 0 },
    { shape: '1x3', color: '#c84bdf', col: 4, row: 0 },
    { shape: '2x1', color: '#c84bdf', col: 4, row: 3 },
    { shape: '2x1', color: '#4caf50', col: 1, row: 0 },
    { shape: '1x2', color: '#4caf50', col: 2, row: 1 },
    { shape: 'mini_J', color: '#29b6f6', col: 0, row: 2 },
    { shape: '1x3', color: '#1976d2', col: 0, row: 3 },
    { shape: 'mini_L', color: '#f44336', col: 2, row: 3 },
  ],
});