// ── Уровень 9 ──────────────────────────────────────────────────
LEVELS.push({
  cols: 9, rows: 9,
  time: 400,
  walls: [
    { color: 'blue', dir: 'top', col: 0, cells: 3 },
    { color: 'red', dir: 'top', col: 3, cells: 1 },
    { color: 'green', dir: 'top', col: 4, cells: 2 },
    { color: 'yellow', dir: 'top', col: 6, cells: 3 },
    { color: 'cyan', dir: 'left', row: 2, cells: 3 },
    { color: 'purple', dir: 'left', row: 5, cells: 3 },
    { color: 'yellow', dir: 'bottom', col: 0, cells: 2 },
    { color: 'blue', dir: 'bottom', col: 2, cells: 1 },
    { color: 'purple', dir: 'bottom', col: 3, cells: 2 },
    { color: 'cyan', dir: 'bottom', col: 5, cells: 2 },
    { color: 'purple', dir: 'bottom', col: 7, cells: 2 },
    { color: 'blue', dir: 'right', row: 1, cells: 3 },
    { color: 'green', dir: 'right', row: 4, cells: 3 },
    { color: 'red', dir: 'right', row: 0, cells: 1 },
  ],
  figures: [
    { shape: '2x1', color: '#f44336', col: 0, row: 0 },
    { shape: '2x1', color: '#ffc107', col: 0, row: 1, axis: 'y' },
    { shape: '2x1', color: '#1976d2', col: 0, row: 2, axis: 'x' },
    { shape: 'L', color: '#29b6f6', col: 0, row: 3 },
    { shape: '1x1', color: '#f44336', col: 0, row: 8 },
    { shape: '2x2', color: '#ffc107', col: 1, row: 3, outlineColor: '#c84bdf' },
    { shape: 'J', color: '#ffc107', col: 1, row: 6 },
    { shape: '1x2', color: '#f44336', col: 1, row: 6 },
    { shape: 'T', color: '#c84bdf', col: 3, row: 3, outlineColor: '#29b6f6' },
    { shape: 'S', color: '#1976d2', col: 3, row: 5, outlineColor: '#4caf50' },
    { shape: '1x3', color: '#4caf50', col: 5, row: 6 },
    { shape: 'mini_J', color: '#4caf50', col: 7, row: 7 },
    { shape: '2x1', color: '#c84bdf', col: 7, row: 6, axis: 'y' },
    { shape: '1x1', color: '#c84bdf', col: 7, row: 4, axis: 'y' },
    { shape: 'Z', color: '#ffc107', col: 3, row: 1, outlineColor: '#1976d2' },
    { shape: '1x4', color: '#ffc107', col: 6, row: 0 },
    { shape: 'mini_J', color: '#c84bdf', col: 7, row: 0 },
    { shape: 'mini_L', color: '#1976d2', col: 7, row: 2 },
    { shape: '1x3', color: '#ffc107', col: 2, row: 0 },
    { shape: '1x1', color: '#f44336', col: 7, row: 5 },
    { shape: '1x1', color: '#f44336', col: 5, row: 4 },
  ],
});