// ── Уровень 9 ──────────────────────────────────────────────────
LEVELS.push({
  cols: 8, rows: 8,
  time: 192,
  walls: [
    { color: 'yellow', dir: 'top', col: 0, cells: 2 },
    { color: 'purple', dir: 'top', col: 2, cells: 2 },
    { color: 'green', dir: 'top', col: 4, cells: 2 },
    { color: 'cyan', dir: 'left', row: 0, cells: 3 },
    { color: 'green', dir: 'left', row: 3, cells: 1 },
    { color: 'yellow', dir: 'left', row: 4, cells: 2 },
    { color: 'purple', dir: 'right', row: 2, cells: 3 },
    { color: 'blue', dir: 'right', row: 5, cells: 1 },
    { color: 'red', dir: 'right', row: 6, cells: 2 },
    { color: 'cyan', dir: 'bottom', col: 5, cells: 3 },
    { color: 'purple', dir: 'bottom', col: 2, cells: 3 },
  ],
  blocks: [
    { shape: '1x1', col: 7, row: 0 },
    { shape: '1x1', col: 7, row: 1 },
    { shape: '1x1', col: 6, row: 0 },
    { shape: '1x1', col: 0, row: 6 },
    { shape: '1x1', col: 0, row: 7 },
    { shape: '1x1', col: 1, row: 7 },
  ],
  figures: [
    { shape: 'J', color: '#4caf50', col: 6, row: 2 },
    { shape: 'L', color: '#29b6f6', col: 0, row: 1, outlineColor: '#ffc107' },
    { shape: 'mini_L', color: '#4caf50', col: 0, row: 4 },
    { shape: '1x1', color: '#4caf50', col: 2, row: 5 },
    { shape: '1x1', color: '#1976d2', col: 1, row: 6 },
    { shape: '2x1', color: '#29b6f6', col: 5, row: 1 },
    { shape: '1x2', color: '#4caf50', col: 4, row: 0 },
    { shape: '1x2', color: '#4caf50', col: 6, row: 5 },
    { shape: 'mini_L', color: '#29b6f6', col: 2, row: 6 },
    { shape: 'mini_J', color: '#c84bdf', col: 3, row: 6, axis: 'y' },
    { shape: 'mini_J', color: '#c84bdf', col: 0, row: 0 },
    { shape: 'T', color: '#29b6f6', col: 1, row: 2, outlineColor: '#ffc107' },
    { shape: 'mini_J', color: '#c84bdf', col: 5, row: 2, outlineColor: '#29b6f6' },
    { shape: 'mini_J', color: '#29b6f6', col: 4, row: 3 },
    { shape: '1x1', color: '#1976d2', col: 4, row: 2 },
    { shape: 'mini_J', color: '#ffc107', col: 2, row: 4, axis: 'x' },
  ],
});